version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=demo_proto
      # - MYSQL_USER=gorm
      # - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_RANDOM_ROOT_PASSWORD="no"
  # redis:
  #   image: 'redis:latest'
  #   ports:
  #     - 6379:6379
